sudo: required
services:
  - docker

before-build:
  - docker build -t gbmonmon/docker-react:latest -f Dockerfile.dev .


script:
  - docker container run gbmonmon/docker-react:latest npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-963718745185"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_LEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
